### ISSUE TITLE
annoying log of files

### ISSUE THREAD

**Issue by heavybeard** [alan-agius4/speedy-build-angular#33]
Is it a development remnant log?

https://github.com/alan-agius4/speedy-build-angular/blob/13f891043042f8c6e39b3f922feed13d61cfdc48/src/index.ts#L30

![image](https://user-images.githubusercontent.com/12038447/68481732-48bd2180-0238-11ea-964e-0e5493bd7dea.png)

**Comment by alan-agius4** [comment]
Oops thanks for pointing that out. Will fix in the coming days

**Comment by alan-agius4** [comment]
fixed in 0.3.0
