### ISSUE TITLE
Add possibility to config ignorePath of stylelint CLI

### ISSUE THREAD

**Issue by biolauri** [alan-agius4/speedy-build-angular#37]
In stylelint, it is possible to use a `.gitignore`-like file as an ignore file. According to its [docs on stylelint ignore configuration](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#stylelintignore), it's possible to specify a path to an ignore file with `--ignore-path` (or `ignorePath`).

I would like to configure this via this builder in the builder options and configurations and use the `.gitignore` file itself. In the [schema.json](../blob/master/src/schema.json), I couldn't this as an option.

**Comment by alan-agius4** [comment]
There are two ways to achive this;

Create a `.stylelintignore ` file or use the `--exclude` option

**Comment by biolauri** [comment]
Thanks for your super fast reply!
Yeah, I know these options, but they work different: I have to maintain another ignore file just for stylelint and can not use my already maintained `.gitignore` file.

---

This shouldn't be that hard as stylelint already supports that options and I only have to pass it through. Maybe, I'll find some time over the weekend. Then I'll open a pull request, if it's okay. :relaxed:

**Comment by biolauri** [comment]
I managed to get some time. It's working for me locally in another repository. If I can improve anything, just let me know!
